open_system('gm_lab2_01');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_lab2_01/CALC_MAGNITUDE_AND_PHASE_FIXED_POINT/Add', 'user2');
annotate_port('gm_lab2_01/CALC_MAGNITUDE_AND_PHASE_FIXED_POINT/Add', 0, 1, 'cp : 21.123 ns');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'blue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_lab2_01/CALC_MAGNITUDE_AND_PHASE_FIXED_POINT/Complex to Real-Imag1', 'user1');
annotate_port('gm_lab2_01/CALC_MAGNITUDE_AND_PHASE_FIXED_POINT/Complex to Real-Imag1', 0, 1, 'cp : 0 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_lab2_01/CALC_MAGNITUDE_AND_PHASE_FIXED_POINT/Product', 'user2');
annotate_port('gm_lab2_01/CALC_MAGNITUDE_AND_PHASE_FIXED_POINT/Product', 0, 1, 'cp : 8.636 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_lab2_01/CALC_MAGNITUDE_AND_PHASE_FIXED_POINT/Sqrt', 'user2');
annotate_port('gm_lab2_01/CALC_MAGNITUDE_AND_PHASE_FIXED_POINT/Sqrt', 1, 1, 'cp : 27.373 ns');
